services:
   db:
      image: postgres
      container_name:  django_tenants_db
      volumes:
         - tenants_postgres_data:/var/lib/postgresql
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
         - DATABASE_PORT=${DATABASE_PORT}
      ports:
         - ${POSTGRES_PORT}:5432

volumes:
   tenants_postgres_data: